### ISSUE TITLE
Problems of downloading dataset

### ISSUE THREAD

**Issue by popo919** [maZZZu/bmfr#2]
Hi.
I've encountered a problem when downloading dataset from the given website. The total size of the dataset is 18G, however, every time I've downloaded 1G the connection is lost. 
Do you know why?

Thanks!
Leong.

**Comment by maZZZu** [comment]
Hi,

Same thing happens on my machine. Thanks for letting us know. I have contacted the people administrating that system. Hopefully they are able to fix it soon.

BR,
// Matias

**Comment by popo919** [comment]
It seems the links are now totally disabled. It prompts "Internal Server Error" when I click them.

**Comment by maZZZu** [comment]
I contacted the administrators of that system and they still didn't know how long it will take them to fix the download. Our university forces us to use that system, but since this is getting ridiculous I uploaded the files here:

https://drive.google.com/open?id=1p9dxNr1txwemUi9p7x1Dzoc1ofu5vg9R

https://drive.google.com/open?id=1_MWktRx66JS4-KlTgGgcIzz_ixgEAaeL

Sorry for the inconvenience caused by this.

**Comment by maZZZu** [comment]
The original file storage system should now work.
