### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by hmfann** [maZZZu/bmfr#4]
Hi.
1. I noticed that the `world_pos` data in .exr file is already scaled to [0, 1] range, and I want to know how this is implemented? For example how to scale `world_pos = vec3(100.0f, 140.0f, 150.0f)` to [0, 1] range?
2. Is the parameter 'position_limit_squared(normal_limit_squared)' set with experience or some statistics?

Thanks!

**Comment by maZZZu** [comment]
1. They are not scaled to range [0, 1]. Randomly checking one .exr gave range [-0.71, 8.77]. If you get only [0, 1] world positions your exr reader must be clamping them. Changing the ranges afterwards would break the motion vector calculations with the camera matrices. If I remember correctly, what could make you think that there is some scaling is that Sponza model was scaled in world space by something like 0.02x before rendering. This was done because the used renderer had some bug if there were too big values.

2. We tested different limit values and then tuned them. It is actually easy to see if the limits are too big or too small for a given scene. Too big values make data bleed from object to another and too small discard data within one object.

Let me know if something is still unclear.
